[project]
name = 'Pharmaceutical-Supply-Chain-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.drug-batch]
path = 'contracts/drug-batch.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-control-nft]
path = 'contracts/quality-control-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.transport-condition]
path = 'contracts/transport-condition.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
